// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ViewsSourceGenerator
{
    using System.Text;
    using System.Collections.Generic;
    using ViewsSourceGenerator.Tools;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal partial class ViewClassTemplate : ViewClassTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// ------------------------------------------------------------------------------\r\n// <auto-generated>\r\n//     This code was generated by a tool.\r\n//  \r\n//     Changes to this file may cause incorrect behavior and will be lost if\r\n//     the code is regenerated.\r\n// </auto-generated>\r\n// ------------------------------------------------------------------------------\r\n#nullable enable\r\n\r\n");
	foreach (var oneUsing in Usings) { 
            
            this.Write(this.ToStringHelper.ToStringWithCulture(oneUsing));
            
            #line default
            #line hidden
            this.Write("\r\n");
  } 
            this.Write("\r\n");
if (HasNamespace) {
            this.Write("namespace ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(NamespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
}
            this.Write("    public partial class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
	foreach (var info in ButtonMethodCallInfo) { 
		for (var i = 0; i < info.CallInfos.Length; i++) { 
			var callInfo = info.CallInfos[i]; 
			if (callInfo.InactivePeriodMs > 0) { 
            this.Write("\t\tprivate float ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(info.GetLastClickFieldName(i)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
          } 
      } 
 } 
            this.Write("\r\n\t\tprivate ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewModelClassName));
            
            #line default
            #line hidden
            this.Write("? _model;\r\n\t\tprivate CompositeDisposable? _oneInitDisposable;\r\n        private ChangeCheckedValue<bool> _isInitiated;\r\n\r\n\t\tpublic void Init(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewModelClassName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n\t\t{\r\n\t\t\tif (!_isInitiated.TryFlip(true))\r\n\t\t\t{\r\n\t\t\t\treturn;\r\n\t\t\t}\r\n\r\n\t\t\t_model = model;\r\n\t\t\t\r\n\t\t\t_oneInitDisposable?.Dispose();\r\n\t\t\t_oneInitDisposable = new CompositeDisposable();\r\n\r\n\t\t\tPreManualInit(model);\r\n\r\n");
	foreach (var subViewInfo in SubViewInfos) { 
		if (subViewInfo.CheckForNull) { 
            this.Write("\t\t\tif (");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.ViewFieldName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t{\r\n\t\t\t\t");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.GetInitCall()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t}\r\n");
      } else { 
            this.Write("\t\t\t");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.GetInitCall()));
            
            #line default
            #line hidden
            this.Write("\r\n");
      } 
  } 
            this.Write("\r\n");
	foreach (var subViewsCollectionInfo in SubViewsCollectionInfos) { 
		foreach (var statement in subViewsCollectionInfo.GetInitCall()) { 
            this.Write("            ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(statement));
            
            #line default
            #line hidden
            this.Write("\r\n");
      } 
  } 
            this.Write("\r\n");
	foreach (var observableBindingInfo in ObservableBindingInfos) { 
		if (observableBindingInfo.CheckForNull) { 
            this.Write("\t\t\tif (");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.FieldName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t{\r\n\t\t\t\tmodel.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.ObservableName));
            
            #line default
            #line hidden
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.DelayIfNeeded()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t.Subscribe(observedValue => { ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.GenerateAssignment("observedValue")));
            
            #line default
            #line hidden
            this.Write("})\r\n\t\t\t\t.AddTo(_oneInitDisposable);\r\n\t\t\t}\r\n");
      } else { 
            this.Write("\t\t\tmodel.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.ObservableName));
            
            #line default
            #line hidden
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.DelayIfNeeded()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t.Subscribe(observedValue => { ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(observableBindingInfo.GenerateAssignment("observedValue")));
            
            #line default
            #line hidden
            this.Write("})\r\n\t\t\t\t.AddTo(_oneInitDisposable);\r\n");
      } 
            this.Write("\r\n");
  } 
	foreach (var info in ButtonMethodCallInfo) { 
            this.Write("\r\n");
		foreach (var statement in info.GetSubscribing()) { 
            this.Write("\t\t\t");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(statement));
            
            #line default
            #line hidden
            this.Write("\r\n");
      } 
 } 
            this.Write("        \r\n");
	foreach (var localizableFieldInfo in LocalizationFieldInfos) { 
		if (localizableFieldInfo.CheckForNull) { 
            this.Write("\t\t\tif (");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(localizableFieldInfo.ViewFieldName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t{\r\n\t\t\t\tmodel.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(localizableFieldInfo.LocalizationKey.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t.AsObservable()\r\n\t\t\t\t\t.Subscribe(text => ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(localizableFieldInfo.PathToLocalizableText));
            
            #line default
            #line hidden
            this.Write(" = text)\r\n\t\t\t\t\t.AddTo(_oneInitDisposable);\r\n\t\t\t}\r\n");
      } else { 
            this.Write("\t\t\tmodel.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(localizableFieldInfo.LocalizationKey.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t.AsObservable()\r\n\t\t\t\t.Subscribe(text => ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(localizableFieldInfo.PathToLocalizableText));
            
            #line default
            #line hidden
            this.Write(" = text)\r\n\t\t\t\t.AddTo(_oneInitDisposable);\r\n");
      } 
            this.Write("\r\n");
  } 
	foreach (var info in SubscribeOnObservableInfos) { 
            this.Write("\t\t\tmodel\r\n\t\t\t\t.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(info.ObservableName));
            
            #line default
            #line hidden
            this.Write("\r\n");
      if (info.HasFilter) { 
            this.Write("\t\t\t\t.Where(observableValue => observableValue ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(info.Filter));
            
            #line default
            #line hidden
            this.Write(")\r\n");
      } 
            this.Write("\t\t\t\t.Subscribe(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(info.GetSubscriptionInnerCode()));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t.AddTo(_oneInitDisposable);\r\n");
  } 
            this.Write("\r\n\t\t\tManualInit(model);\r\n\t\t}\r\n\t\t\r\n\t\tpublic void Deinit()\r\n\t\t{\r\n\t\t\tif (!_isInitiated.TryFlip(false))\r\n\t\t\t{\r\n\t\t\t\treturn;\r\n\t\t\t}\r\n");
	foreach (var subViewInfo in SubViewInfos) { 
		if (subViewInfo.CheckForNull) { 
            this.Write("\t\t\tif (");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.ViewFieldName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\t{\r\n\t\t\t\t");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.GetDeinitCall()));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t}\r\n");
      } else { 
            this.Write("\t\t\t");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(subViewInfo.GetDeinitCall()));
            
            #line default
            #line hidden
            this.Write("\r\n");
      } 
  } 
            this.Write("\r\n");
	foreach (var subViewsCollectionInfo in SubViewsCollectionInfos) { 
		foreach (var statement in subViewsCollectionInfo.GetDeinitCall()) { 
            this.Write("            ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(statement));
            
            #line default
            #line hidden
            this.Write("\r\n");
      } 
  } 
            this.Write("\r\n\t\t\tManualDeinit();\r\n\r\n\t\t\t_oneInitDisposable?.Dispose();\r\n\t\t\t_oneInitDisposable = null;\r\n\t\t\t\r\n\t\t\t_model = null;\r\n\t\t}\r\n\r\n\t\tprivate void OnDestroy()\r\n\t\t{\r\n\t\t\t_oneInitDisposable?.Dispose();\r\n\t\t\t_oneInitDisposable = null;\r\n\r\n\t\t\tManualOnDestroy();\r\n\t\t}\r\n\r\n\t\tpartial void ManualInit(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewModelClassName));
            
            #line default
            #line hidden
            this.Write(" model);\r\n\r\n\t\tpartial void PreManualInit(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ViewModelClassName));
            
            #line default
            #line hidden
            this.Write(" model);\r\n\r\n\t\tpartial void ManualDeinit();\r\n\r\n\t\tpartial void ManualOnDestroy();\r\n    }\r\n");
if (HasNamespace) {
            this.Write("}\r\n");
}
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    internal class ViewClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
